version: '3'
services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    environment:
      - VERSION=latest
      - TZ=America/New_York
      - PLEX_CLAIM=claim-s2XC4gzsLZczRdYJgBgu
    network_mode: "host"
    volumes:
      - /home/donald/docker/plex/database:/config
      - /home/donald/docker/plex/transcode:/transcode
      - /home/donald/docker/plex/media:/data
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes: 
      - /home/donald/docker/qbittorrent/config:/config
      - /home/donald/docker/plex/media/tv:/tv
      - /home/donald/docker/plex/media/movies:/movies
      - /home/donald/docker/qbittorrent/downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /home/donald/docker/sonarr/config:/config
      - /home/donald/docker/plex/media/tv:/tv
      - /home/donald/docker/qbittorrent/downloads:/downloads
    environment:
      - TZ=America/New_York
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes: 
      - /home/donald/docker/radarr/config:/config
      - /home/donald/docker/plex/media/movies:/movies
      - /home/donald/docker/qbittorrent/downloads:/downloads
    environment:
      - TZ=America/New_York
    ports:
      - 7878:7878
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports: 
      - 9000:9000
    volumes: 
      - /home/donald/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
